name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag
        id: increment_tag
        run: echo "::set-output name=incremented_tag::$(echo ${{ steps.get_tag.outputs.tag }} | awk -F'[+]' '/+/{$1+=1} 1')"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.incremented_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.incremented_tag }}
          draft: false
          prerelease: false
