name: Auto Release and Tag

on:
  push:
    branches:
      - master

jobs:
  create_release_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Set up Git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
  
      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Determine next tag
        id: determine_next_tag
        run: |
          latest_tag=${{ steps.get_tag.outputs.tag }}
          # Add logic to generate the next tag based on the latest tag
          # Example: Increment the last digit of the tag
          next_tag=$(echo $latest_tag | awk -F'[+]' '/+/{$1+=1} 1')
          echo "::set-output name=next_tag::$next_tag"

      - name: Create tag
        run: git tag ${{ steps.determine_next_tag.outputs.next_tag }}

      - name: Push tag
        run: git push origin ${{ steps.determine_next_tag.outputs.next_tag }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.determine_next_tag.outputs.next_tag }}
          release_name: Release ${{ steps.determine_next_tag.outputs.next_tag }}
          draft: false
          prerelease: false
